default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: docker

test:
  <<: *default
  database: docker_test

production:
  <<: *default
  database: docker_prod
